
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
buildDrafts = false
baseURL = "https://comic-cms.netlify.com/"
canonifyURLs = true
title = "Webcomic CMS"
sectionPagesMenu = "main"
paginate = 10
paginatePath = "archive"

[taxonomies]
  chapter = "chapters"
  tag = "tags"
  author = "authors"
  character = "characters"

[params]
  subtitle = "a webcomic site"
  author = "Sarah Frisk"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = -10