contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
assetDir = "static"
buildDrafts = false
baseURL = "https://comic-cms.netlify.com"
canonifyURLs = true
title = "Webcomic CMS"
sectionPagesMenu = "main"
paginate = 10
paginatePath = "archive"
theme = "webcomic"

[outputs]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "S Frisk"
  subtitle = "a webcomic site"
  og_description = "test"
  og_image = ""
  og_site_name = "Webcomic CMS"
  twitter_site = "@TavernWenches"
  twitter_creator = "@SarahFrisk"
  twitter_image = ""
  creator = ""
  og_type = "website"
  og_local = "en-US"
  facebook = ""
  tumblr = ""
  twitter = ""
  instagram = ""
  youtube = ""
  twitch = ""
