backend:
  name: github
  repo: sfrisk/webcomics-cms

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: page
    label: Pages
    files:
      - name: 'home'
        label: 'Home'
        file: "content/_index.md"
        fields:
          - {name: title, label: Title}
          - {name: weight, label: Weight, widget: number }
          - {name: body, label: Body, widget: markdown}
      - name: 'cast'
        label: 'Cast'
        file: "content/character/_index.md"
        fields:
          - {name: title, label: Title}
          - {name: weight, label: Weight, widget: number }
          - {name: body, label: Body, widget: markdown}
      - name: 'comic-index'
        label: 'Comic'
        file: "content/comic/_index.md"
        fields:
          - {name: pageTitle, label: Title}
          - {name: title, label: Navigation Title}
          - {name: weight, label: Weight, widget: number }
          - {name: rssTitle, label: RSS Feed Title}
          - {name: body, label: Body, widget: markdown}
  - name: character
    label: Character
    folder: content/character
    filter: {field: "type", value: "character"}
    create: true
    fields:
      - {name: title, label: Name}
      - {name: type, value: character, widget: hidden}
      - {name: featured, label: Featured, value: false, widget: boolean}
      - {name: thumbnail, label: Thumbnail, widget: image}
      - {label: Description, name: body, widget: markdown}
  - name: news
    label: News
    folder: content/news
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: body, label: Body, widget: markdown}
  - name: comic
    label: Comic
    folder: content/comic
    create: true
    filter: {field: "type", value: "comic"}
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: type, value: comic, widget: hidden}
      - label: Characters
        name: characters
        widget: relation
        collection: character
        searchFields: [title]
        valueField: title
        displayFields: [title]
        multiple: true
      - name: comic_header_mobile
        label: Comic Header (Mobile)
        required: false
        widget: image
      - name: comic_footer_mobile
        label: Comic Footer (Mobile)
        required: false
        widget: image
      - name: comic_desktop
        label: Desktop Comic Image (Upload a 2x version of your comic here)
        required: false
        widget: image
      - name: comic_mobile
        label: Mobile Comic Image (Upload a 760px wide version of your comic for mobile devices)
        widget: image
        required: false
      - name: comic
        label: Comic (Panel By Panel - Use this to upload each panel individually to be used in both mobile/desktop layouts)
        widget: object
        fields:
          - label: Rows
            name: rows
            widget: list
            fields:
              - label: Panels
                name: cols
                widget: list
                fields:
                  - name: panel
                    label: Panel
                    widget: image
                  - name: transcript
                    label: Transcript
                    widget: markdown
      - {name: body, label: Body, widget: markdown}
      - {name: transcript, label: Comic Transcript (Full), widget: markdown, required: false}
      - {name: thumbnail, label: Thumbnail (Appears in Comic Archive), widget: image}
      - {name: og_title, label: Social Share Title, widget: string, required: false}
      - {name: og_image, label: Social Share Image (1200 x 630px), widget: image, required: false}
      - {name: og_description, label: Social Share Description, widget: text, required: false}
      - {name: og_type, widget: hidden, default: article}
