backend:
  name: github
  repo: sfrisk/webcomics-cms

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: page
    label: Page
    folder: content
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
  # - name: character
  #   label: Character
  #   folder: data/characters
  #   create: true
  #   extension: toml
  #   fields:
  #     - {name: title, label: Title}
  #     - {name: thumbnail, label: Thumbnail, widget: image}
  #     - {label: Description, name: description, widget: markdown}
  - name: character
    label: Character
    folder: content/characters
    create: true
    fields:
      - {name: title, label: Title}
      - {name: name, label: Name}
      - {name: thumbnail, label: Thumbnail, widget: image}
      - {label: Description, name: description, widget: markdown}
  - name: post
    label: Post
    folder: content/post
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: body, label: Body, widget: markdown}
  - name: comic
    label: Comic
    folder: content/comic
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - label: Characters
        name: characters
        widget: relation
        collection: character
        searchFields: [title]
        valueField: title
        displayFields: [title]
        multiple: true
      - name: comic
        label: Comic
        widget: object
        fields:
          - label: Rows
            name: rows
            widget: list
            fields:
              - label: Panels
                name: cols
                widget: list
                fields:
                  - name: panel
                    label: Panel
                    widget: image
      - {name: thumbnail, label: Thumbnail, widget: image}
      - {name: og_title, label: Social Share Title, widget: string}
      - {name: og_image, label: Social Share Image (1200 x 630px), widget: image}
      - {name: og_description, label: Social Share Description, widget: text}
      - {name: og_type, widget: hidden, default: article}
