backend:
  name: github
  repo: sfrisk/webcomics-cms

media_folder: static/assets/images
public_folder: assets/images
# publish_mode: editorial_workflow

collections:
  - name: page
    label: Pages
    files:
      - name: 'home'
        label: 'Home'
        file: "content/_index.md"
        preview_path: ""
        fields:
          - {name: title, label: Title}
          - {name: weight, label: Weight, widget: number }
          - {name: body, label: Body, widget: markdown}
          - {name: bannerImage, label: Banner Image, widget: image}
          - label: Featured Characters
            name: featuredCharacters
            widget: relation
            collection: character
            searchFields: [title]
            valueField: title
            displayFields: [title]
            multiple: true
      - name: 'cast'
        label: 'Cast'
        file: "content/character/_index.md"
        preview_path: "character/"
        fields:
          - {name: title, label: Title}
          - {name: weight, label: Weight, widget: number }
          - {name: body, label: Body, widget: markdown}
      - name: 'comic-index'
        label: 'Comic'
        file: "content/comic/_index.md"
        preview_path: "comic/"
        fields:
          - {name: pageTitle, label: Title}
          - {name: title, label: Navigation Title}
          - {name: weight, label: Weight, widget: number }
          - {name: rssTitle, label: RSS Feed Title}
          - {name: body, label: Body, widget: markdown}
  - name: chapter
    label: Chapter
    folder: data/chapters
    create: true
    extension: json
    fields:
      - {name: title, label: Chapter Title}
      - {name: number, label: Chapter Number, widget: number}
      - {name: description, label: Description, widget: text}
  - name: character
    label: Character
    slug: "{{slug}}"
    folder: content/character
    preview_path: "character/{{slug}}/"
    filter: {field: "type", value: "character"}
    create: true
    fields:
      - {name: title, label: Name}
      - {name: type, value: character, widget: hidden}
      - {name: characterType, label: Type, widget: select, multiple: false, options: ['wench', 'npc', 'pc', 'other']}
      - {name: featured, label: Featured, value: false, required: false, widget: boolean}
      - {name: thumbnail, label: Thumbnail, widget: image}
      - {label: Description, name: body, widget: markdown}
      - label: Character Sheet
        name: characterSheet
        widget: object
        required: false
        fields:
          - {name: class, label: Class, widget: select, required: false, multiple: false, options: [Barbarian, Bard, Cleric, Druid, Fighter, Monk, Paladin, Ranger, Rogue, Sorcerer, Warlock, Wizard]}
          - {name: level, label: Level, widget: number, required: false, valueType: int }
          - {name: race, label: Race, widget: select, required: false, multiple: false, options: [Dragonborn, Dwarf, Elf, Gnome, Half-Elf, Halfling, Half-Orc, Human, Tiefling]}
          - {name: size, label: Size, widget: select, required: false, multiple: false, options: [Small, Medium]}
          - {name: alignment, label: Alignment, widget: select, required: false, options: [Lawful Good, Neutral Good, Chaotic Good, Lawful Neutral, Neutral, Chaotic Neutral, Lawful Evil, Neutral Evil, Chaotic Evil]}
          - {name: speed, label: Speed, widget: number, required: false, valueType: int }
          - {name: hp, label: Hit Points, widget: number, required: false}
          - {name: ac, label: Armor Class, widget: number, required: false}
          - name: abilityScores
            label: Ability Scores
            widget: object
            required: false
            fields:
              - {name: str, label: Strength, widget: number, required: false, valueType: int}
              - {name: dex, label: Dexterity, widget: number, required: false, valueType: int}
              - {name: con, label: Constitution, widget: number, required: false, valueType: int}
              - {name: int, label: Intelligence, widget: number, required: false, valueType: int}
              - {name: wis, label: Wisdom, widget: number, required: false, valueType: int}
              - {name: cha, label: Charisma, widget: number, required: false, valueType: int}
          - {name: proficiencyBonus, label: Proficiency Bonus, widget: number, required: false, valueType: int}
          - {name: savingThrows, label: Saving Throws, widget: select, required: false, multiple: true, options: [str, dex, con, int, wis, cha]}
          - {name: skills, label: Skills, widget: select, required: false, multiple: true, options: [Athletics, Acrobatics, Sleight of Hand, Stealth, Arcana, History, Investigation, Nature, Religion, Animal Handling, Insight, Medicine, Perception, Survival, Deception, Intimidiation, Performance, Persuasion]}
          - {name: languages, label: Languages, widget: select, required: false, multiple: true, options: [Common, Dwarvish, Elvish, Giant, Gnomish, Goblin, Halfling, Orc, Abyssal, Celestial, Draconic, Deep Speech, Infernal, Primordial, Sylvan, Undercommon]}
          - {name: armor, label: Armor, required: false}
          - {name: weapons, label: Weapons, required: false}
          - {name: tools, label: Tools, required: false}
          - name: features
            label: Features
            widget: list
            required: false
            fields:
              - {name: title, label: Title, required: false}
              - {name: description, label: Description, required: false}
          - name: spellcasting
            label: Spellcasting
            required: false
            widget: object
            fields:
            - {name: level, label: Spellcaster Level, widget: number, required: false}
              - {name: dcSave, label: DC Save, widget: number, required: false, valueType: int}
              - {name: attack, label: Attack, widget: number, required: false, valueType: int}
              - {name: ability, label: Spellcasting Ability, widget: select, required: false, multiple: false, options: [Intelligence, Wisdom, Charisma]}
              - {name: cantrips, label: Cantrips, required: false}
              - {name: lvl1, label: 1st Level, required: false}
              - {name: lvl1Slots, label: 1st Level Spell Slots, required: false, widget: number}
              - {name: lvl2, label: 2nd Level, required: false}
              - {name: lvl2Slots, label: 2nd Level Spell Slots, required: false, widget: number}
              - {name: lvl3, label: 3rd Level, required: false}
              - {name: lvl3Slots, label: 3rd Level Spell Slots, required: false, widget: number}
              - {name: lvl4, label: 4th Level, required: false}
              - {name: lvl4Slots, label: 4th Level Spell Slots, required: false, widget: number}
          - name: actions
            label: Actions
            widget: list
            required: false
            fields:
              - {name: title, label: Title, required: false}
              - {name: description, label: Description, required: false}
          - name: roleplaying
            label: Roleplaying Info
            widget: object
            required: false
            fields:
            - {name: background, label: Background, required: false}
            - {name: event, label: Defining Event, required: false}
            - {name: trait, label: Personality Trait, required: false}
            - {name: ideal, label: Ideal, required: false}
            - {name: bond, label: Bond, required: false}
            - {name: flaw, label: Flaw, required: false}
          - name: equipment
            label: Equipment
            widget: list
            required: false
            fields:
              - {name: item, label: Item, required: false}
          - {name: trinket, label: Trinket, required: false}
  - name: news
    slug: "{{slug}}"
    label: News
    folder: content/news
    create: true
    preview_path: "news/{{slug}}/"
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: body, label: Body, widget: markdown}
  - name: comic
    slug: "{{chapter}}/{{slug}}"
    label: Comic
    folder: content/comic
    create: true
    preview_path: "comic/{{slug}}/"
    filter: {field: "type", value: "comic"}
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: type, value: comic, widget: hidden}
      - label: Chapter
        name: chapter
        widget: relation
        collection: chapter
        searchFields: [title, number]
        valueField: title
        displayFields: [title, number]
        multiple: false
        required: true
      - label: Characters
        name: characters
        widget: relation
        collection: character
        searchFields: [title]
        valueField: title
        displayFields: [title]
        multiple: true
        required: false
      - name: comic
        label: Comic (Panel By Panel - Use this to upload each panel individually to be used in both mobile/desktop layouts)
        widget: object
        fields:
          - label: Rows
            name: rows
            widget: list
            required: false
            fields:
              - label: Panels
                name: cols
                widget: list
                required: false
                fields:
                  - name: panel
                    label: Panel
                    widget: image
                    required: false
                  - name: transcript
                    label: Transcript
                    widget: markdown
                    required: false
      - {name: thumbnail, label: Thumbnail (Appears in Comic Archive), widget: image}
      - {name: og_title, label: Social Share Title, widget: string, required: false}
      - {name: og_image, label: Social Share Image (1200 x 630px), widget: image, required: false}
      - {name: og_description, label: Social Share Description, widget: text, required: false}
      - {name: og_type, widget: hidden, default: article}
