backend:
  name: github
  repo: sfrisk/webcomics-cms

media_folder: media_folder

collections:
  - name: page
    label: Page
    folder: src/pages
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
      - {name: layout, label: Layout, widget: "select", options: ['posts.html', 'page.html']}
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: body, label: Body, widget: markdown}
      - {name: layout, label: Layout, widget: hidden, default: 'post.html'}
  - name: comic
    label: Comic
    folder: src/comics
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: datetime}
      - {name: layout, label: Layout, widget: hidden, default: 'comic.html'}
      - name: panels
        label: Panels
        widget: list
        fields:
          - {label: Row, name: row, widget: number}
          - {label: Column, name: column, widget: number}
          - {label: Image, name: image, widget: image} 